import type { Metadata } from "next";
import { Manrope, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.variable} ${jetbrainsMono.variable} antialiased`}
      >
        {/* Prevent FOUC: set initial theme before hydration */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
            (function(){
              try {
                var saved = localStorage.getItem('theme');
                var d = document.documentElement;
                if (saved === 'dark') {
                  d.classList.add('dark');
                  d.removeAttribute('data-theme');
                } else {
                  d.setAttribute('data-theme','light');
                  d.classList.remove('dark');
                }
              } catch (e) {
                document.documentElement.setAttribute('data-theme','light');
                document.documentElement.classList.remove('dark');
              }
            })();
          `,
          }}
        />
        {children}
      </body>
    </html>
  );
}
